# Generated by Django 2.2.6 on 2019-11-13 21:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import task.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='whitePaper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('WPFile', models.FileField(upload_to='', validators=[task.models.validate_file_ext])),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('dueTime', models.DateTimeField()),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(auto_now=True)),
                ('uploader', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('77a4cace-681e-456e-9d3a-a3e85c2b0d2b'), editable=False, primary_key=True, serialize=False)),
                ('video_url', models.URLField()),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(auto_now=True)),
                ('WP', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='task.whitePaper')),
                ('uploader', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='testQuestions',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('65a7ae95-3ebc-4b26-96bd-e3fcbf165faa'), editable=False, primary_key=True, serialize=False)),
                ('q1', models.TextField()),
                ('a1', models.TextField()),
                ('a2', models.TextField()),
                ('a3', models.TextField()),
                ('a4', models.TextField()),
                ('CA', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('WP', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='task.whitePaper')),
                ('uploader', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
