# Generated by Django 2.2.6 on 2019-11-13 22:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20191113_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestions',
            name='id',
            field=models.UUIDField(default=uuid.UUID('17b88742-91ff-478a-b17a-1a19b2509b67'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='videos',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d1d8b3f9-a733-4d5c-9e37-724499786d7b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
