# Generated by Django 2.2.6 on 2019-11-13 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20191113_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestions',
            name='id',
            field=models.UUIDField(default=uuid.UUID('82f7d9ed-1059-47a4-89b0-8d1fea4f1dba'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='videos',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f0e84c84-54c0-4283-945c-f70c185eb528'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='whitepaper',
            name='acceptor',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='acceptor', to=settings.AUTH_USER_MODEL),
        ),
    ]
