# Generated by Django 2.2.6 on 2019-11-13 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20191113_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestions',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2c6d8f06-e279-4af6-8c24-bde8209139d9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='videos',
            name='id',
            field=models.UUIDField(default=uuid.UUID('06bde66f-ebc7-40da-bb5b-03a78265bb83'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='whitepaper',
            name='acceptor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='acceptor', to=settings.AUTH_USER_MODEL),
        ),
    ]
