# Generated by Django 2.2.6 on 2019-11-13 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20191113_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestions',
            name='WP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.whitePaper'),
        ),
        migrations.AlterField(
            model_name='testquestions',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1c0c551d-8642-4272-82de-2e4c0c1001b2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testquestions',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videos',
            name='WP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.whitePaper'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='id',
            field=models.UUIDField(default=uuid.UUID('33db4181-3879-42d4-822d-29dd31a26c74'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='videos',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='whitepaper',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to=settings.AUTH_USER_MODEL),
        ),
    ]
