# Generated by Django 2.2.6 on 2019-11-13 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20191113_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestions',
            name='id',
            field=models.UUIDField(default=uuid.UUID('326a3444-3686-49de-8cd0-308bf6fc8171'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='videos',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9a6dfa70-a237-4044-aee5-4e5824e582c0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='whitepaper',
            name='acceptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acceptor', to=settings.AUTH_USER_MODEL),
        ),
    ]
