# Generated by Django 2.2.6 on 2019-11-16 00:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20191115_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestions',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8eddfb4e-934d-4872-82d2-169a2f2c28ec'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='videos',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5a680720-0098-480b-9324-201108f4988f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
