# Generated by Django 2.2.7 on 2019-11-28 07:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_auto_20191127_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='wpClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='wpQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.TextField()),
                ('a1', models.TextField()),
                ('a2', models.TextField()),
                ('a3', models.TextField()),
                ('a4', models.TextField()),
                ('CA', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
            ],
        ),
        migrations.RemoveField(
            model_name='videos',
            name='WP',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='uploader',
        ),
        migrations.AlterField(
            model_name='whitepaper',
            name='dueTime',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='testQuestions',
        ),
        migrations.DeleteModel(
            name='videos',
        ),
        migrations.AddField(
            model_name='wpquiz',
            name='WP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.whitePaper'),
        ),
        migrations.AddField(
            model_name='wpclass',
            name='WP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.whitePaper'),
        ),
    ]
