# Generated by Django 2.2.7 on 2019-12-06 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0013_auto_20191128_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitepaper',
            name='acceptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wp_acceptor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='wpTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('dueTime', models.DateField()),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(auto_now=True)),
                ('accepted', models.BooleanField(default=False)),
                ('WP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.whitePaper')),
                ('acceptor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_acceptor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='taskFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WPFile', models.FileField(blank=True, null=True, upload_to='')),
                ('wpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.wpTask')),
            ],
        ),
    ]
